name: e2e docs test
on:
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:
  issue_comment:
    types: [created]
jobs:
  run-tests:
    name: run tests
    if: |
      github.event_name == 'pull_request' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/test') &&
      github.event.comment.author_association == 'MEMBER')
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    env:
      PROJECT_ID: substratus-integration-tests
    steps:
      - name: Debugging
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Pull Request: ${{ github.event.issue.pull_request }}"
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Author Association: ${{ github.event.comment.author_association }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          install_components: "gke-gcloud-auth-plugin,kubectl"
          project_id: "substratus-integration-tests"
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: "projects/489627518739/locations/global/workloadIdentityPools/github-identities/providers/github-com"
          service_account: "docs-test-runner@substratus-integration-tests.iam.gserviceaccount.com"
      - name: make test
        run: |
          sudo mkdir -p /home/runner/.kube/ && \
          sudo chown -R runner:runner /home/runner/.kube/ && \
          sudo chmod -R 700 /home/runner/.kube/ && \
          sudo apt-get update -y && \
          sudo apt-get install -y --no-install-recommends \
          python3 \
          python3-pip && \
          make test
